#!/bin/bash

# CoMA Pipeline
# Copyright (C) 2020 Sebastian Hupfauf, Mohammad Etemadi

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# contact
# ------
# coma-mikrobiologie@uibk.ac.at


(zenity --no-wrap --question --title="CoMA" --text "Welcome to CoMA, a pipeline for amplicon sequencing data analysis! 

Do you want to start a new project?
Click 'No' to continue/recalculate an existing project." 2> /dev/null) && shell="Yes" || shell="No"

if [ $shell = "Yes" ]
then

out=$(zenity --forms --title="New project" --text="Alright, let's start a new project!\n\nATTENTION: Please use a project name that does not include any special characters other than '_'!\nFurthermore, the project name must not start with a number on the first position!" --add-entry="Project name" 2> /dev/null)
if [[ $? -eq 1 ]]
then 
exit
fi

pn=$(awk -F '[|]' '{print $1}' <<<$out)

if [ -d "$pn" ]
then

(zenity --no-wrap --question --title="New project" --text "ATTENTION!

This project already exists. Do you really want to overwrite it?
All data will be lost!" 2> /dev/null) && shell="Yes" || shell="No"

if [ $shell = "No" ]
then

exit

fi
fi

mkdir -p $pn
cd $pn
wd=$(pwd)
rm -r * 2> /dev/null
mkdir -p Data

export IFS='
'

files=$(zenity --title "Please select your forward AND reverse sequence files:" --file-selection --multiple 2> /dev/null)

if [[ $? -eq 1 ]]
then 
exit
fi

for i in $(echo $files | tr "|" "\n")
do
cp $i $wd/Data
done

else

wd=$(zenity --title "Please choose your project:" --file-selection --directory 2> /dev/null)

if [[ $? -eq 1 ]]
then 
exit
fi
fi

date=$(date +%d%m%Y_%T)

export wd=$wd
export date=$date

cd $wd
script -c '/usr/local/Pipeline/pipeline_gui.sh' $date.log
